### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by NealSavage** [Jake-E/Myrtrees#11]
What do I do with what I have harvested? Does this mod add any uses?

**Comment by Jake-E** [comment]
There is integration with FTB Industrial Contraptions, otherwise, the mod currently adds no extra content.
https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge

**Comment by NealSavage** [comment]
Oh okay. Any plans to?

**Comment by festelo** [comment]
Any recipes, description of how rubbertrees work? There's no readme at all
