### ISSUE TITLE
[Issue] Crash report

### ISSUE THREAD

**Issue by lostopkk** [Jake-E/Myrtrees#15]
### Mod version

1.19

### Repeatable?

- [ ] Yes

### Link to log files

https://www.toptal.com/developers/hastebin/famekadogi.properties

### Description of the issue you are having

crash

### Information

- [X] I have provided as much information as possible

**Comment by Jake-E** [comment]
Can you provide a list of mods or the modpack so that I can try and reproduce this?
The crash-report is too vague to see what's actually happening.

**Comment by ProsperCraft** [comment]
Original log files are gone, consider posting your logs to gist instead.
